/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class UringHttpServer {
  constructor(options?: ServerOptions | undefined | null)
  start(): ServerInfo
  stop(): void
  info(): ServerInfo | null
}

export declare class UringTcpEchoServer {
  constructor(options?: TcpServerOptions | undefined | null)
  start(): ServerInfo
  stop(): void
  info(): ServerInfo | null
}

export declare class UringTcpServer {
  constructor(options?: TcpServerOptions | undefined | null)
  start(eventCallback: (arg: TcpEvent) => unknown): ServerInfo
  startBatch(eventCallback: (arg: Array<TcpEvent>) => unknown): ServerInfo
  send(connectionId: number, data: Buffer): boolean
  sendAndClose(connectionId: number, data: Buffer): boolean
  sendBatch(sends: Array<TcpSend>): boolean
  sendBatchAndClose(sends: Array<TcpSend>): boolean
  closeConnection(connectionId: number): boolean
  stop(): void
  info(): ServerInfo | null
}

export declare function capabilities(): Capabilities

export interface Capabilities {
  platform: string
  kernelRelease: string
  ioUringAvailable: boolean
  accept: boolean
  acceptMulti: boolean
  recv: boolean
  recvMulti: boolean
  providedBuffers: boolean
  providedBufferRing: boolean
  providedBufferRingProbe: string
  recvBundle: boolean
  send: boolean
  sendZc: boolean
  registeredSendBuffer: boolean
  registeredSendBufferProbe: string
  recvZc: boolean
  zcrxKernelOpcode: boolean
  zcrxCqe32Ring: boolean
  zcrxCqe32RingProbe: string
  fastPoll: boolean
  note: string
}

export interface ServerInfo {
  host: string
  port: number
  backend: string
  backlog: number
  queueDepth: number
  bufferCount: number
  bufferSize: number
  maxConnections: number
  rejectedConnections: number
  idleTimeoutMs: number
  idleTimeouts: number
  tcpNoDelay: boolean
  reusePort: boolean
  tcpDeferAcceptSeconds: number
  socketRecvBufferSize: number
  socketSendBufferSize: number
  commandQueueCapacity: number
  commandQueueDrops: number
  eventQueueCapacity: number
  eventQueueDrops: number
  eventBatchSize: number
  sendQueueCapacity: number
  sendQueueDrops: number
  sendBufferCount: number
  sendBufferSize: number
  activeConnections: number
  acceptedConnections: number
  closedConnections: number
  bytesReceived: number
  bytesSent: number
  multishotAccept: boolean
  multishotRecv: boolean
  providedBufferRing: boolean
  recvBundle: boolean
  recvBundleCompletions: number
  recvBundleBuffers: number
  recvBundleBytes: number
  recvBufferStarvations: number
  recvMultishotResubmits: number
  recvCopyEvents: number
  recvCopyBytes: number
  registeredSendBuffer: boolean
  registeredSendRequests: number
  registeredSendErrors: number
  fixedSendBufferMisses: number
  fixedSendBufferMissBytes: number
  zeroCopySend: boolean
  zeroCopySendRequests: number
  zeroCopySendNotifications: number
  zeroCopySendCopied: number
  zeroCopySendErrors: number
  zeroCopyReceive: boolean
  zcrxReady: boolean
  zcrxRxBufferSize: number
  zcrxPackets: number
  zcrxBytes: number
}

export interface ServerOptions {
  host?: string
  port?: number
  backlog?: number
  queueDepth?: number
  bufferCount?: number
  bufferSize?: number
  maxConnections?: number
  idleTimeoutMs?: number
  tcpNoDelay?: boolean
  reusePort?: boolean
  tcpDeferAcceptSeconds?: number
  socketRecvBufferSize?: number
  socketSendBufferSize?: number
  responseBody?: string
  useRegisteredSendBuffer?: boolean
  useRecvBundle?: boolean
  useZeroCopySend?: boolean
  useZeroCopyReceive?: boolean
  zcrxInterfaceName?: string
  zcrxRxQueue?: number
  zcrxRxBufferSize?: number
}

export interface TcpEvent {
  eventType: string
  connectionId: number
  remoteAddr?: string
  remoteAddress?: string
  remoteFamily?: string
  remotePort?: number
  data?: Buffer
}

export interface TcpSend {
  connectionId: number
  data: Buffer
}

export interface TcpServerOptions {
  host?: string
  port?: number
  backlog?: number
  queueDepth?: number
  bufferCount?: number
  bufferSize?: number
  maxConnections?: number
  idleTimeoutMs?: number
  tcpNoDelay?: boolean
  reusePort?: boolean
  tcpDeferAcceptSeconds?: number
  socketRecvBufferSize?: number
  socketSendBufferSize?: number
  commandQueueCapacity?: number
  eventQueueCapacity?: number
  eventBatchSize?: number
  sendQueueCapacity?: number
  useRegisteredSendBuffer?: boolean
  useRecvBundle?: boolean
  useZeroCopySend?: boolean
  sendBufferCount?: number
  sendBufferSize?: number
  useZeroCopyReceive?: boolean
  zcrxInterfaceName?: string
  zcrxRxQueue?: number
  zcrxRxBufferSize?: number
}

export declare function zcrxProbe(options?: ZcrxProbeOptions | undefined | null): ZcrxProbe

export interface ZcrxProbe {
  interfaceName?: string
  interfaceIndex: number
  kernelOpcode: boolean
  interfaceExists: boolean
  operstate?: string
  rxQueue: number
  rxBufferSize: number
  rxQueueCount: number
  driver?: string
  isLoopback: boolean
  isVirtual: boolean
  ethtoolAvailable: boolean
  headerDataSplit: string
  flowSteering: string
  activeRegistration: boolean
  activeRegistrationResult?: string
  activeRegistrationErrno?: number
  ready: boolean
  blockers: Array<string>
  note: string
}

export interface ZcrxProbeOptions {
  interfaceName?: string
  rxQueue?: number
  rxBufferSize?: number
  activeRegistration?: boolean
}
